#!/bin/sh

fatal () {
    echo "$*" >&@
    exit 1
}

main=${1}
test -x ${main}.exe && main=${1}.exe
test -x ${main} || fatal "${main}: cannot open"
nm ${main} | fgrep -wi t | awk '{print $1, $3}' | sort |
    awk '
BEGIN	{ addr="00000000"
	  prev="";
	  print "(begin"; }
	{ if (NR>1) printf "(pc-map-add 0x%s 0x%s \"%s\")\n", addr, $1, prev;
	  addr=$1;
	  prev=$2; }
END	{ print ")"; }' > ${1}.sym
