/* generated by Id 1.0 at 2007-09-02 14:34:14 Z */
/* with the command: -I../stage1/ -c ByteArray.st -o ../stage2/ByteArray.o.c */

#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <setjmp.h>
#include <string.h>
#include <ctype.h>
#include <fcntl.h>
#include <unistd.h>
#include <time.h>
#include <sys/time.h>
#include <sys/stat.h>
#include <sys/param.h>
#include <assert.h>
#define GC_DLL 1
#include <gc/gc.h>
#if defined(WIN32)
# include <malloc.h>
# include <windows.h>
# include <winbase.h>
  typedef HINSTANCE dlhandle_t;
# define dlopen(path, mode)	LoadLibrary(path)
# define dlsym(handle, name)	((void *)GetProcAddress(handle, name))
# define dlclose(handle)	FreeLibrary(handle)
#else
# include <dlfcn.h>
  typedef void *dlhandle_t;
#endif
#ifndef O_BINARY
# define O_BINARY 0
#endif

typedef struct t__object *oop;

typedef oop (*_imp_t)(oop _thunk, oop receiver, ...);

struct __closure
{
  _imp_t method;
  oop	 data;
};

static void              *(*_local_param   )(int index)= 0;
static oop  		  (*_local_intern  )(const char *string)= 0;
static oop  		  (*_local_proto   )(oop base)= 0;
static oop  		  (*_local_import  )(const char *name)= 0;
static oop  		  (*_local_export  )(const char *name, oop value)= 0;
static void 		  (*_local_method  )(oop type, oop selector, _imp_t method)= 0;
static oop  		  (*_local_alloc   )(oop type, size_t size)= 0;
static oop  		 *(*_local_palloc  )(size_t size)= 0;
static void  		 *(*_local_balloc  )(size_t size)= 0;
static struct __closure  *(*_local_bind    )(oop selector, oop receiver)= 0;
static oop                (*_local_nlreturn)(oop nlr, oop result)= 0;
static oop                (*_local_nlresult)(void)= 0;
static oop  		    _local_object= 0;
static oop  		   *_local_tag_vtable= 0;
static oop  		   *_local_nil_vtable= 0;
static void               (*_local_gc_addRoots)(char *lo, char *hi)= 0;
static void	          (*_local_gc_unregisterDisappearingLink)(void *ptr)= 0;
static void		  (*_local_gc_generalRegisterDisappearingLink)(void *link, void *ptr)= 0;
static void		  (*_local_gc_gcollect)(void)= 0;
static void		 *(*_local_enter)(char *name, char *type, char *file)= 0;
static void		  (*_local_line)(int line)= 0;
static void		  (*_local_leave)(void *)= 0;
static char		 *(*_local_backtrace)(void)= 0;

#define _param(INDEX)		_local_param(INDEX)
#define _selector(NAME)		_local_intern(NAME)
#define _proto(BASE)		_local_proto(BASE)
#define _id_import(NAME)	_local_import(NAME)
#define _id_export(NAME, VAL)	_local_export((NAME), (VAL))
#define _method(TYPE, SEL, IMP)	_local_method((TYPE), (SEL), (_imp_t)(IMP))
#define _alloc(RCV, LBS)	_local_alloc((RCV), (LBS))
#define _palloc(LBS)		_local_palloc((LBS))
#define _balloc(LBS)		_local_balloc((LBS))
#define _nlreturn(NLR, ARG)	_local_nlreturn((NLR), (ARG))
#define _nlresult()		_local_nlresult()
#define _backtrace()		_local_backtrace()
#ifdef ID_DEBUG
# define _enter(NM, TYPE, FILE)	void *__id_debug= _local_enter(NM, TYPE, FILE)
# define _line(line)		_local_line(line)
# define _leave()		_local_leave(__id_debug)
#else
# define _enter(NM, TYPE, FILE)
# define _line(line)
# define _leave()
#endif
#define _return			_leave(); return

#define _send(MSG, RCV, ARG...) ({					\
  register oop _r= (RCV);						\
  struct __closure *_c= (struct __closure *)_local_bind((MSG), _r);	\
  (_c->method)((oop)_c, _r, _r, ##ARG);					\
})

#define _super(TYP, MSG, RCV, ARG...) ({				\
  register oop _r= (RCV);						\
  struct __closure *_c= (struct __closure *)_local_bind((MSG), (TYP));	\
  (_c->method)((oop)_c, _r, _r, ##ARG);					\
})

static oop s__3c_3d= 0;
static oop s_byteAt_= 0;
static oop s_value_5f_= 0;
static oop s_species= 0;
static oop s__5fimport_= 0;
static oop s_ifFalse_= 0;
static oop s__5fbytes= 0;
static oop s__5felements= 0;
static oop s__2d= 0;
static oop s__2b= 0;
static oop s_size= 0;
static oop s__5fclone= 0;
static oop s_primitiveFailed= 0;
static oop s_size_5f_value_5f_= 0;
static oop s_size_value_5f_= 0;
static oop s_isByteArray= 0;
static oop s_initialize_= 0;
static oop s_byteAt_put_= 0;
static oop s_elementSize= 0;
static oop s_replaceFrom_to_with_startingAt_= 0;
static oop s_and_= 0;
static oop s_replaceFrom_5f_for_5f_with_5f_startingAt_5f_= 0;
static oop s__5fintegerValue= 0;
static oop s_errorImmutable= 0;
static oop s_at_= 0;
static oop s__5fnewBytes_= 0;
static oop s_at_put_= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { "<=", &s__3c_3d },
  { "byteAt:", &s_byteAt_ },
  { "value_:", &s_value_5f_ },
  { "species", &s_species },
  { "_import:", &s__5fimport_ },
  { "ifFalse:", &s_ifFalse_ },
  { "_bytes", &s__5fbytes },
  { "_elements", &s__5felements },
  { "-", &s__2d },
  { "+", &s__2b },
  { "size", &s_size },
  { "_clone", &s__5fclone },
  { "primitiveFailed", &s_primitiveFailed },
  { "size_:value_:", &s_size_5f_value_5f_ },
  { "size:value_:", &s_size_value_5f_ },
  { "isByteArray", &s_isByteArray },
  { "initialize:", &s_initialize_ },
  { "byteAt:put:", &s_byteAt_put_ },
  { "elementSize", &s_elementSize },
  { "replaceFrom:to:with:startingAt:", &s_replaceFrom_to_with_startingAt_ },
  { "and:", &s_and_ },
  { "replaceFrom_:for_:with_:startingAt_:", &s_replaceFrom_5f_for_5f_with_5f_startingAt_5f_ },
  { "_integerValue", &s__5fintegerValue },
  { "errorImmutable", &s_errorImmutable },
  { "at:", &s_at_ },
  { "_newBytes:", &s__5fnewBytes_ },
  { "at:put:", &s_at_put_ },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Character {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Fraction {
  struct _vtable *_vtable[0];
  oop v_numerator;
  oop v_denominator;
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargePositiveInteger {
  struct _vtable *_vtable[0];
  oop v_bytes;
};
struct t_LargeNegativeInteger {
  struct _vtable *_vtable[0];
  oop v_bytes;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_ImmutableArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_WordArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__words;
};
struct t_ImmutableWordArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__words;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_ImmutableByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_ImmutableString {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
struct t_CharacterTable {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
static oop l_1= 0;
static oop l_2= 0;
static oop v__object= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_StaticBlockClosure= 0;
static oop v_Magnitude= 0;
static oop v_Number= 0;
static oop v_Integer= 0;
static oop v_SmallInteger= 0;
static oop v_LargePositiveInteger= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_ArrayedCollection= 0;
static oop v_Array= 0;
static oop v_WordArray= 0;
static oop v_ByteArray= 0;
static oop v_ImmutableByteArray= 0;
static oop v_String= 0;
static oop v_ImmutableString= 0;
static oop v_true= 0;
static oop v_false= 0;
static oop ByteArray__species(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter("species", "ByteArray", "/home/piumarta/src/idst/object/st80/ByteArray.st");
  oop _1= 0;
  _line(25);
  _1= v_ByteArray;
  _leave();
  return _1;
  _leave();
 }
static oop Object__isByteArray(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter("isByteArray", "Object", "/home/piumarta/src/idst/object/st80/ByteArray.st");
  oop _1= 0;
  _line(27);
  _1= v_false;
  _leave();
  return _1;
  _leave();
 }
static oop ByteArray__isByteArray(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter("isByteArray", "ByteArray", "/home/piumarta/src/idst/object/st80/ByteArray.st");
  oop _1= 0;
  _line(28);
  _1= v_true;
  _leave();
  return _1;
  _leave();
 }
static oop ByteArray__size_value_5f_(oop v__closure, oop v_stateful_self, oop v_self, oop v_byteSize, oop v__value)
 {
  _enter("size:value_:", "ByteArray", "/home/piumarta/src/idst/object/st80/ByteArray.st");
  oop _1= 0;
  _line(30);
  _1= v_self;
  _line(32);
  _1=_send(s__5fclone, _1);
  v_self= _1;
  v_stateful_self= _1;
  _1= v_byteSize;
  ((struct t_ByteArray *)v_stateful_self)->v_size= _1;
  _1= v__value;
  ((struct t_ByteArray *)v_stateful_self)->v__bytes= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static oop ByteArray__size_5f_value_5f_(oop v__closure, oop v_stateful_self, oop v_self, oop v__size, oop v__value)
 {
  _enter("size_:value_:", "ByteArray", "/home/piumarta/src/idst/object/st80/ByteArray.st");
  oop _1= 0;
  oop _2= 0;
  _line(37);
  _1= v_self;
  _line(39);
  _1=_send(s__5fclone, _1);
  v_self= _1;
  v_stateful_self= _1;
  _1= v_SmallInteger;
  _2= v__size;
  _line(40);
  _1=_send(s_value_5f_, _1, _2);
  ((struct t_ByteArray *)v_stateful_self)->v_size= _1;
  _1= v__value;
  ((struct t_ByteArray *)v_stateful_self)->v__bytes= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static oop ByteArray__initialize_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anInteger)
 {
  _enter("initialize:", "ByteArray", "/home/piumarta/src/idst/object/st80/ByteArray.st");
  oop _1= 0;
  oop _2= 0;
  _line(44);
  _1= v_self;
  _2= v_anInteger;
  _line(46);
  _1=_super(v_ArrayedCollection, s_initialize_, _1, _2);
  _1= v_self;
  _2= v_anInteger;
  _line(47);
  _1=_send(s__5fnewBytes_, _1, _2);
  ((struct t_ByteArray *)v_stateful_self)->v__bytes= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static oop ByteArray___5fbytes(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter("_bytes", "ByteArray", "/home/piumarta/src/idst/object/st80/ByteArray.st");
  oop _1= 0;
  _line(50);
  _1= ((struct t_ByteArray *)v_stateful_self)->v__bytes;
  _leave();
  return _1;
  _leave();
 }
static oop ByteArray___5felements(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter("_elements", "ByteArray", "/home/piumarta/src/idst/object/st80/ByteArray.st");
  oop _1= 0;
  _line(51);
  _1= ((struct t_ByteArray *)v_stateful_self)->v__bytes;
  _leave();
  return _1;
  _leave();
 }
static oop ByteArray__byteAt_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anInteger)
 {
  _enter("byteAt:", "ByteArray", "/home/piumarta/src/idst/object/st80/ByteArray.st");
  oop _1= 0;
  _line(53);
 {
# define self ((struct t_ByteArray *)v_self)
 if (((int)v_anInteger & 1) && ((int)v_anInteger > 1) && ((int)v_anInteger <= (int)self->v_size))
        return (oop)((((int)(((unsigned char *)self->v__bytes)[((int)v_anInteger >> 1) - 1])) << 1) | 1); 
# undef self
 }
  _1= 0;
  _1= v_self;
  _line(57);
  _1=_send(s_primitiveFailed, _1);
  _leave();
  return _1;
  _leave();
 }
static oop ByteArray__byteAt_put_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anInteger, oop v_aByte)
 {
  _enter("byteAt:put:", "ByteArray", "/home/piumarta/src/idst/object/st80/ByteArray.st");
  oop _1= 0;
  _line(60);
 {
# define self ((struct t_ByteArray *)v_self)

      if (((int)v_anInteger & 1) && ((int)v_anInteger > 1) && ((int)v_anInteger <= (int)self->v_size) && ((int)v_aByte & 1))
        {
          ((char *)self->v__bytes)[((int)v_anInteger >> 1) - 1]= (int)v_aByte >> 1;
          return v_aByte;
        }
    
# undef self
 }
  _1= 0;
  _1= v_self;
  _line(69);
  _1=_send(s_primitiveFailed, _1);
  _leave();
  return _1;
  _leave();
 }
static oop ByteArray__at_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anInteger)
 {
  _enter("at:", "ByteArray", "/home/piumarta/src/idst/object/st80/ByteArray.st");
  oop _1= 0;
  oop _2= 0;
  _line(72);
  _1= v_self;
  _2= v_anInteger;
  _line(72);
  _1=_send(s_byteAt_, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static oop ByteArray__at_put_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anInteger, oop v_aByte)
 {
  _enter("at:put:", "ByteArray", "/home/piumarta/src/idst/object/st80/ByteArray.st");
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(73);
  _1= v_self;
  _2= v_anInteger;
  _3= v_aByte;
  _line(73);
  _1=_send(s_byteAt_put_, _1, _2, _3);
  _leave();
  return _1;
  _leave();
 }
static oop ByteArray__elementSize(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter("elementSize", "ByteArray", "/home/piumarta/src/idst/object/st80/ByteArray.st");
  oop _1= 0;
  _line(75);
  _1= l_1;
  _leave();
  return _1;
  _leave();
 }
static oop ByteArray__replaceFrom_to_with_startingAt_(oop v__closure, oop v_stateful_self, oop v_self, oop v_first, oop v_last, oop v_bytes, oop v_offset)
 {
  _enter("replaceFrom:to:with:startingAt:", "ByteArray", "/home/piumarta/src/idst/object/st80/ByteArray.st");
  oop v_count= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  oop _4= 0;
  oop _5= 0;
  (void)v_count;
  _line(77);
  _1= v_last;
  _2= v_first;
  {
    int _l= (int)_1 >> 1;
    int _r= (int)_2 >> 1;
    int _s= (_l - _r);
    if ((1 & (int)_1 & (int)_2) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(_s << 1 | 1);  else _1= _send(s__2d, _1, _2);
  }
  _2= l_2;
  {
    int _l= (int)_1 >> 1;
    int _r= (int)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (int)_1) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(_s << 1 | 1);  else _1= _send(s__2b, _1, _2);
  }
  v_count= _1;
  /* ifFalse: */
  _1= 0;
  /* and: */
  _2= v_bytes;
  _line(81);
  _2=_send(s_isByteArray, _2);
  if (!_2) goto _l2;
 {
  /* and: */
  _2= l_2;
  _3= v_first;
  if (1 & (int)_3) {
    _2= (((int)_2 <= (int)_3) ? v_true : v_false);
  } else _2= _send(s__3c_3d, _2, _3);
  if (!_2) goto _l3;
 {
  /* and: */
  _2= v_first;
  _3= v_last;
  if (1 & (int)_2 & (int)_3) {
    _2= (((int)_2 <= (int)_3) ? v_true : v_false);
  } else _2= _send(s__3c_3d, _2, _3);
  if (!_2) goto _l4;
 {
  /* and: */
  _2= v_last;
  _3= v_self;
  _line(84);
  _3=_send(s_size, _3);
  if (1 & (int)_2 & (int)_3) {
    _2= (((int)_2 <= (int)_3) ? v_true : v_false);
  } else _2= _send(s__3c_3d, _2, _3);
  if (!_2) goto _l5;
 {
  /* and: */
  _2= l_2;
  _3= v_offset;
  if (1 & (int)_3) {
    _2= (((int)_2 <= (int)_3) ? v_true : v_false);
  } else _2= _send(s__3c_3d, _2, _3);
  if (!_2) goto _l6;
 {
  _2= v_offset;
  _3= v_count;
  {
    int _l= (int)_2 >> 1;
    int _r= (int)_3 >> 1;
    int _s= _l + _r;
    if ((1 & (int)_2 & (int)_3) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(_s << 1 | 1);  else _2= _send(s__2b, _2, _3);
  }
  _3= l_2;
  {
    int _l= (int)_2 >> 1;
    int _r= (int)_3 >> 1;
    int _s= (_l - _r);
    if ((1 & (int)_2) && ((_s ^ (_s << 1)) >= 0))  _2= (oop)(_s << 1 | 1);  else _2= _send(s__2d, _2, _3);
  }
  _3= v_bytes;
  _line(86);
  _3=_send(s_size, _3);
  if (1 & (int)_2 & (int)_3) {
    _2= (((int)_2 <= (int)_3) ? v_true : v_false);
  } else _2= _send(s__3c_3d, _2, _3);
 }
 _l6:;
 }
 _l5:;
 }
 _l4:;
 }
 _l3:;
 }
 _l2:;
  if (_2) goto _l1;
 {
  _1= v_self;
  _2= v_first;
  _3= v_last;
  _4= v_bytes;
  _5= v_offset;
  _line(87);
  _1=_super(v_ArrayedCollection, s_replaceFrom_to_with_startingAt_, _1, _2, _3, _4, _5);
  _leave();
  return _1;
 }
 _l1:;
  _1= v_self;
  _2= v_first;
  _line(88);
  _2=_send(s__5fintegerValue, _2);
  _3= v_count;
  _line(89);
  _3=_send(s__5fintegerValue, _3);
  _4= v_bytes;
  _line(90);
  _4=_send(s__5fbytes, _4);
  _5= v_offset;
  _line(91);
  _5=_send(s__5fintegerValue, _5);
  _line(88);
  _1=_send(s_replaceFrom_5f_for_5f_with_5f_startingAt_5f_, _1, _2, _3, _4, _5);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static oop ByteArray__replaceFrom_5f_for_5f_with_5f_startingAt_5f_(oop v__closure, oop v_stateful_self, oop v_self, oop v__first, oop v__count, oop v__source, oop v__offset)
 {
  _enter("replaceFrom_:for_:with_:startingAt_:", "ByteArray", "/home/piumarta/src/idst/object/st80/ByteArray.st");
  oop _1= 0;
  _line(94);
 {
# define self ((struct t_ByteArray *)v_self)

    memcpy((char *)self->v__bytes + (int)v__first - 1, (char *)v__source + (int)v__offset - 1, (int)v__count);

# undef self
 }
  _1= 0;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static oop ImmutableByteArray__at_put_(oop v__closure, oop v_stateful_self, oop v_self, oop v_anInteger, oop v_aByte)
 {
  _enter("at:put:", "ImmutableByteArray", "/home/piumarta/src/idst/object/st80/ByteArray.st");
  oop _1= 0;
  _line(102);
  _1= v_self;
  _line(104);
  _1=_send(s_errorImmutable, _1);
  _leave();
  return _1;
  _leave();
 }
static oop ImmutableByteArray__replaceFrom_to_with_startingAt_(oop v__closure, oop v_stateful_self, oop v_self, oop v_first, oop v_last, oop v_bytes, oop v_offset)
 {
  _enter("replaceFrom:to:with:startingAt:", "ImmutableByteArray", "/home/piumarta/src/idst/object/st80/ByteArray.st");
  oop _1= 0;
  _line(107);
  _1= v_self;
  _line(109);
  _1=_send(s_errorImmutable, _1);
  _leave();
  return _1;
  _leave();
 }

void __id__init__ByteArray(void)
{
  if (_local_object) return;
  { 
    dlhandle_t global= dlopen(0, RTLD_LAZY);
    _local_object= *(oop *)dlsym(global, "_libid_object");
    _local_param= dlsym(global, "_libid_param");
    _local_intern= dlsym(global, "_libid_intern");
    _local_proto= dlsym(global, "_libid_proto");
    _local_import= dlsym(global, "_libid_import");
    _local_export= dlsym(global, "_libid_export");
    _local_method= dlsym(global, "_libid_method");
    _local_alloc= dlsym(global, "_libid_alloc");
    _local_palloc= dlsym(global, "_libid_palloc");
    _local_balloc= dlsym(global, "_libid_balloc");
    _local_bind= dlsym(global, "_libid_bind");
    _local_nlreturn= dlsym(global, "_libid_nlreturn");
    _local_nlresult= dlsym(global, "_libid_nlresult");
    _local_enter= dlsym(global, "_libid_enter");
    _local_line= dlsym(global, "_libid_line");
    _local_leave= dlsym(global, "_libid_leave");
    _local_backtrace= dlsym(global, "_libid_backtrace");
    _local_tag_vtable= dlsym(global, "_libid_tag_vtable");
    _local_nil_vtable= dlsym(global, "_libid_nil_vtable");
    _local_gc_addRoots= dlsym(global, "GC_add_roots");
    _local_gc_unregisterDisappearingLink= dlsym(global, "GC_unregister_disappearing_link");
    _local_gc_generalRegisterDisappearingLink= dlsym(global, "GC_general_register_disappearing_link");
    _local_gc_gcollect= dlsym(global, "GC_gcollect");
    dlclose(global);
  }
# define GC_add_roots _local_gc_addRoots
  GC_INIT();
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _selector(s->name);
  }
  _enter("__id__init__", "<initialisation>", "ByteArray.st");

  _send(s__5fimport_, _local_object, "ArrayedCollection", "__id__init__ArrayedCollection");
  _send(s__5fimport_, _local_object, "SequenceableCollection", "__id__init__SequenceableCollection");
  _send(s__5fimport_, _local_object, "Collection", "__id__init__Collection");
  _send(s__5fimport_, _local_object, "Object", "__id__init__Object");
  _send(s__5fimport_, _local_object, "_object", "__id__init___5fobject");
  v__object= _id_import("_object");
  v_Object= _id_import("Object");
  v_UndefinedObject= _id_import("UndefinedObject");
  v_StaticBlockClosure= _id_import("StaticBlockClosure");
  v_Magnitude= _id_import("Magnitude");
  v_Number= _id_import("Number");
  v_Integer= _id_import("Integer");
  v_SmallInteger= _id_import("SmallInteger");
  v_LargePositiveInteger= _id_import("LargePositiveInteger");
  v_Collection= _id_import("Collection");
  v_SequenceableCollection= _id_import("SequenceableCollection");
  v_ArrayedCollection= _id_import("ArrayedCollection");
  v_Array= _id_import("Array");
  v_WordArray= _id_import("WordArray");
  v_ByteArray= _id_import("ByteArray");
  v_ImmutableByteArray= _id_import("ImmutableByteArray");
  v_String= _id_import("String");
  v_ImmutableString= _id_import("ImmutableString");
  v_true= _id_import("true");
  v_false= _id_import("false");
  _send(s__5fimport_, _local_object, "BlockClosure", "__id__init__BlockClosure");
  _send(s__5fimport_, _local_object, "SmallInteger", "__id__init__SmallInteger");
  _send(s__5fimport_, _local_object, "Integer", "__id__init__Integer");
  _send(s__5fimport_, _local_object, "Number", "__id__init__Number");
  _send(s__5fimport_, _local_object, "Magnitude", "__id__init__Magnitude");
  _send(s__5fimport_, _local_object, "Array", "__id__init__Array");
  _send(s__5fimport_, _local_object, "Character", "__id__init__Character");
  _send(s__5fimport_, _local_object, "String", "__id__init__String");
  _send(s__5fimport_, _local_object, "ByteArray", "__id__init__ByteArray");
  _send(s__5fimport_, _local_object, "WordArray", "__id__init__WordArray");
  _method(v_ByteArray, s_species, ByteArray__species);
  _method(v_Object, s_isByteArray, Object__isByteArray);
  _method(v_ByteArray, s_isByteArray, ByteArray__isByteArray);
  _method(v_ByteArray, s_size_value_5f_, ByteArray__size_value_5f_);
  _method(v_ByteArray, s_size_5f_value_5f_, ByteArray__size_5f_value_5f_);
  _method(v_ByteArray, s_initialize_, ByteArray__initialize_);
  _method(v_ByteArray, s__5fbytes, ByteArray___5fbytes);
  _method(v_ByteArray, s__5felements, ByteArray___5felements);
  _method(v_ByteArray, s_byteAt_, ByteArray__byteAt_);
  _method(v_ByteArray, s_byteAt_put_, ByteArray__byteAt_put_);
  _method(v_ByteArray, s_at_, ByteArray__at_);
  _method(v_ByteArray, s_at_put_, ByteArray__at_put_);
  l_1= _send(s_value_5f_, v_SmallInteger, 1);
  _method(v_ByteArray, s_elementSize, ByteArray__elementSize);
  l_2= _send(s_value_5f_, v_SmallInteger, 1);
  _method(v_ByteArray, s_replaceFrom_to_with_startingAt_, ByteArray__replaceFrom_to_with_startingAt_);
  _method(v_ByteArray, s_replaceFrom_5f_for_5f_with_5f_startingAt_5f_, ByteArray__replaceFrom_5f_for_5f_with_5f_startingAt_5f_);
  _method(v_ImmutableByteArray, s_at_put_, ImmutableByteArray__at_put_);
  _method(v_ImmutableByteArray, s_replaceFrom_to_with_startingAt_, ImmutableByteArray__replaceFrom_to_with_startingAt_);
  _leave();
}
