/* generated by Id 1.1 at ,$ */
/* with the command: -I../stage1/ -I../st80 -c CodeGenerator.st -o ../stage2/CodeGenerator.o.c */

#include <id/id.h>

static struct __libid *_libid= 0;

#ifdef ID_DEBUG
# define _enter(info) void *__id_debug= _libid->enter(info)
# define _line(lno)			_libid->line(lno)
# define _leave()			_libid->leave(__id_debug)
# define _backtrace()			_libid->backtrace()
#else
# define _enter(info)			(void)info
# define _line(lno)
# define _leave()
# define _backtrace()			"(no debugging information)\n"
#endif
#define _return			_leave(); return

#define _sendv(MSG, N, RCV, ARG...) ({					\
  struct __send _s= { (MSG), (N), (RCV) };				\
  ((_imp_t)(_libid->bindv(&_s)))(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

#define _superv(TYP, MSG, N, RCV, ARG...) ({	\
  struct __send _s= { (MSG), (N), (TYP) };	\
  _imp_t _imp= _libid->bindv(&_s);		\
  _s.receiver= (RCV);				\
  _imp(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

static oop s_new_5f_= 0;
static oop s_encoder= 0;
static oop s_withCompiler_encoder_= 0;
static oop s_at_ifAbsent_= 0;
static oop s_forExecutionModel_= 0;
static oop s__5fdebugName= 0;
static oop s_new= 0;
static oop s__5fimport_= 0;
static oop s_size_5f_value_5f_= 0;
static oop s_function_5f_arity_5f_outer_state_nlr_5f_= 0;
static oop s_value_5f_= 0;
static oop s__5fslots= 0;
static oop s__2c= 0;
static oop s_error_= 0;
static oop s__5fsizeof= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { "new_:", &s_new_5f_ },
  { "encoder", &s_encoder },
  { "withCompiler:encoder:", &s_withCompiler_encoder_ },
  { "at:ifAbsent:", &s_at_ifAbsent_ },
  { "forExecutionModel:", &s_forExecutionModel_ },
  { "_debugName", &s__5fdebugName },
  { "new", &s_new },
  { "_import:", &s__5fimport_ },
  { "size_:value_:", &s_size_5f_value_5f_ },
  { "function_:arity_:outer:state:nlr_:", &s_function_5f_arity_5f_outer_state_nlr_5f_ },
  { "value_:", &s_value_5f_ },
  { "_slots", &s__5fslots },
  { ",", &s__2c },
  { "error:", &s_error_ },
  { "_sizeof", &s__5fsizeof },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Character {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Fraction {
  struct _vtable *_vtable[0];
  oop v_numerator;
  oop v_denominator;
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargePositiveInteger {
  struct _vtable *_vtable[0];
  oop v_bytes;
};
struct t_LargeNegativeInteger {
  struct _vtable *_vtable[0];
  oop v_bytes;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_ImmutableArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_WordArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__words;
};
struct t_ImmutableWordArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__words;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_ImmutableByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_ImmutableString {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
struct t_CharacterTable {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_Set {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
};
struct t_LookupKey {
  struct _vtable *_vtable[0];
  oop v_key;
};
struct t_Association {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t_OrderedCollection {
  struct _vtable *_vtable[0];
  oop v_array;
  oop v_firstIndex;
  oop v_lastIndex;
};
struct t_Dictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
};
struct t_SymbolTable {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
};
struct t_IdentitySet {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
};
struct t_IdentityDictionary {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
};
struct t_SlotVariableNode {
  struct _vtable *_vtable[0];
  oop v_name;
  oop v_position;
  oop v_scope;
  oop v_receiver;
  oop v_type;
};
struct t_EncodedVariableNode {
  struct _vtable *_vtable[0];
  oop v_name;
  oop v_position;
  oop v_scope;
  oop v_offset;
};
struct t_LocalVariableNode {
  struct _vtable *_vtable[0];
  oop v_name;
  oop v_position;
  oop v_scope;
  oop v_offset;
  oop v_index;
};
struct t_ArgumentVariableNode {
  struct _vtable *_vtable[0];
  oop v_name;
  oop v_position;
  oop v_scope;
  oop v_offset;
  oop v_index;
  oop v_tied;
};
struct t_TemporaryVariableNode {
  struct _vtable *_vtable[0];
  oop v_name;
  oop v_position;
  oop v_scope;
  oop v_offset;
  oop v_index;
};
struct t_Scope {
  struct _vtable *_vtable[0];
  oop v_tally;
  oop v_array;
  oop v_argumentCount;
  oop v_temporaryCount;
  oop v_stackSize;
  oop v_outer;
  oop v_blocks;
  oop v_tag;
  oop v_level;
  oop v_lastOffset;
  oop v_encodings;
  oop v_exportFlag;
  oop v_importFlag;
  oop v_nlrFlag;
  oop v_hasVarargs;
};
struct t_ParseNode {
  struct _vtable *_vtable[0];
  oop v_position;
  oop v_location;
};
struct t_VariableNode {
  struct _vtable *_vtable[0];
  oop v_position;
  oop v_location;
  oop v_name;
  oop v_variable;
  oop v_level;
};
struct t_LiteralNode {
  struct _vtable *_vtable[0];
  oop v_position;
  oop v_location;
  oop v_value;
  oop v_tag;
  oop v_constructor;
};
struct t_IntegerNode {
  struct _vtable *_vtable[0];
  oop v_position;
  oop v_location;
  oop v_value;
  oop v_tag;
  oop v_constructor;
};
struct t_SendNode {
  struct _vtable *_vtable[0];
  oop v_position;
  oop v_location;
  oop v_receiver;
  oop v_selector;
  oop v_arguments;
  oop v_cascades;
  oop v_superedType;
  oop v_specialGenerator;
};
struct t_GlobalVariableNode {
  struct _vtable *_vtable[0];
  oop v_name;
  oop v_position;
  oop v_scope;
  oop v_offset;
};
struct t_Encoder {
  struct _vtable *_vtable[0];
  oop v_globalContext;
  oop v_globals;
  oop v_scope;
  oop v_tempCount;
  oop v_tempMax;
  oop v_outerCount;
  oop v_selectors;
  oop v_literals;
  oop v_literalMap;
  oop v_literalTag;
  oop v_methodType;
  oop v_specialEncoders;
  oop v_implementations;
  oop v_knownSelectors;
};
struct t_NameManglingTable {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_Smalltalk {
  struct _vtable *_vtable[0];
  oop v_argumentCount;
  oop v_argumentVector;
};
struct t_CodeGenerator {
  struct _vtable *_vtable[0];
  oop v_compiler;
  oop v_encoder;
  oop v_nextLabel;
};
static oop l_3= 0;
static oop l_5= 0;
static oop v__object= 0;
static oop v__vector= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_StaticBlockClosure= 0;
static oop v_BlockClosure= 0;
static oop v_Magnitude= 0;
static oop v_Number= 0;
static oop v_Integer= 0;
static oop v_SmallInteger= 0;
static oop v_LargePositiveInteger= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_ArrayedCollection= 0;
static oop v_Array= 0;
static oop v_WordArray= 0;
static oop v_ByteArray= 0;
static oop v_String= 0;
static oop v_ImmutableString= 0;
static oop v_Set= 0;
static oop v_LookupKey= 0;
static oop v_Dictionary= 0;
static oop v_IdentityDictionary= 0;
static oop v_EncodedVariableNode= 0;
static oop v_LocalVariableNode= 0;
static oop v_ParseNode= 0;
static oop v_LiteralNode= 0;
static oop v_CodeGenerator= 0;
static oop v_CodeGenerators= 0;
static size_t CodeGenerator___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_CodeGenerator); }
static char *CodeGenerator___5fdebugName(oop _closure, oop v_self) { return "CodeGenerator"; }
static struct __slotinfo *CodeGenerator___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "compiler", 0, 4 }, { "encoder", 4, 4 }, { "nextLabel", 8, 4 }, { 0, 0, 0 } };  return &info[0]; }
static struct __methodinfo __info2= { "[] forExecutionModel:", "CodeGenerator", "/Users/piumarta/src/idst/object/idc/CodeGenerator.st", 0, 30, 35, 0 };
static oop b_2(oop v__closure, oop v__self)
 {
  _enter(&__info2);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(32);
  _1= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[1];  /* self */
  _2= l_3;
  _3= ((oop *)((struct t_BlockClosure *)((struct t_BlockClosure *)v__self)->v_state))[3];  /* modelSymbol */
  _line(32);
  _2=_sendv(s__2c, 2, _2, _3);
  _line(32);
  _1=_sendv(s_error_, 2, _1, _2);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info1= { "forExecutionModel:", "CodeGenerator", "/Users/piumarta/src/idst/object/idc/CodeGenerator.st", 0, 30, 35, &__info2 };
static oop CodeGenerator__forExecutionModel_(oop v__closure, oop v_stateful_self, oop v_self, oop v_modelSymbol)
 {
  _enter(&__info1);
  oop _state1= _sendv(s_new_5f_, 2, v__vector, 7);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  ((oop *)_state1)[2]= v_stateful_self;
  ((oop *)_state1)[1]= v_self;
  ((oop *)_state1)[3]= v_modelSymbol;
  _line(30);
  _1= v_CodeGenerators;
  _2= ((oop *)_state1)[3];  /* modelSymbol */
  /* Scope() */
  /* Scope('compiler'->SlotVariableNode 'encoder'->SlotVariableNode 'self'->ArgumentVariableNode 'nextLabel'->SlotVariableNode 'modelSymbol'->ArgumentVariableNode 'stateful_self'->ArgumentVariableNode) */
  /* nil */
  /* 2 */
  /* 1 */
  _3= _sendv(s_function_5f_arity_5f_outer_state_nlr_5f_, 6, v_BlockClosure, (oop)b_2, 0, 0, ((oop *)_state1), 0);
  _line(32);
  _1=_sendv(s_at_ifAbsent_, 3, _1, _2, _3);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info4= { "withCompiler:encoder:", "CodeGenerator", "/Users/piumarta/src/idst/object/idc/CodeGenerator.st", 0, 35, 43, &__info1 };
static oop CodeGenerator__withCompiler_encoder_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aCompiler, oop v_anEncoder)
 {
  _enter(&__info4);
  oop _1= 0;
  _line(35);
  _1= v_self;
  _line(37);
  _1=_sendv(s_new, 1, _1);
  v_self= _1;
  v_stateful_self= _1;
  _1= v_aCompiler;
  ((struct t_CodeGenerator *)v_stateful_self)->v_compiler= _1;
  _1= v_anEncoder;
  ((struct t_CodeGenerator *)v_stateful_self)->v_encoder= _1;
  _1= l_5;
  ((struct t_CodeGenerator *)v_stateful_self)->v_nextLabel= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info6= { "encoder", "CodeGenerator", "/Users/piumarta/src/idst/object/idc/CodeGenerator.st", 0, 43, 44, &__info4 };
static oop CodeGenerator__encoder(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info6);
  oop _1= 0;
  _line(43);
  _1= ((struct t_CodeGenerator *)v_stateful_self)->v_encoder;
  _leave();
  return _1;
  _leave();
 }

static struct __methodinfo __info= { "__id__init__", "<initialisation>", "CodeGenerator.st", 0, 0, 0, &__info6 };
void __id__init__CodeGenerator(struct __libid *__libid)
{
  if (_libid) return;
  if (!(_libid= __libid)) { fprintf(stderr, "init _libid %p\n", __libid);  abort(); }
# define GC_add_roots _libid->gc_addRoots
  GC_INIT();
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _libid->intern(s->name);
  }
  _enter(&__info);
  _libid->infos(&__info, &__info2);

  _sendv(s__5fimport_, 3, _libid->_object, "Object", "__id__init__Object");
  v__object= _libid->import("_object");
  v__vector= _libid->import("_vector");
  v_Object= _libid->import("Object");
  v_UndefinedObject= _libid->import("UndefinedObject");
  v_StaticBlockClosure= _libid->import("StaticBlockClosure");
  v_BlockClosure= _libid->import("BlockClosure");
  v_Magnitude= _libid->import("Magnitude");
  v_Number= _libid->import("Number");
  v_Integer= _libid->import("Integer");
  v_SmallInteger= _libid->import("SmallInteger");
  v_LargePositiveInteger= _libid->import("LargePositiveInteger");
  v_Collection= _libid->import("Collection");
  v_SequenceableCollection= _libid->import("SequenceableCollection");
  v_ArrayedCollection= _libid->import("ArrayedCollection");
  v_Array= _libid->import("Array");
  v_WordArray= _libid->import("WordArray");
  v_ByteArray= _libid->import("ByteArray");
  v_String= _libid->import("String");
  v_ImmutableString= _libid->import("ImmutableString");
  _sendv(s__5fimport_, 3, _libid->_object, "Symbol", "__id__init__Symbol");
  v_Set= _libid->import("Set");
  v_LookupKey= _libid->import("LookupKey");
  v_Dictionary= _libid->import("Dictionary");
  _sendv(s__5fimport_, 3, _libid->_object, "IdentityDictionary", "__id__init__IdentityDictionary");
  v_IdentityDictionary= _libid->import("IdentityDictionary");
  _sendv(s__5fimport_, 3, _libid->_object, "Encoder", "__id__init__Encoder");
  v_EncodedVariableNode= _libid->import("EncodedVariableNode");
  v_LocalVariableNode= _libid->import("LocalVariableNode");
  v_ParseNode= _libid->import("ParseNode");
  v_LiteralNode= _libid->import("LiteralNode");
  _sendv(s__5fimport_, 3, _libid->_object, "Smalltalk", "__id__init__Smalltalk");
  v_CodeGenerator= _libid->proto2(v_Object, CodeGenerator___5fsizeof(0, 0));
  _libid->method(v_CodeGenerator, s__5fsizeof, (_imp_t)CodeGenerator___5fsizeof);
  _libid->method(v_CodeGenerator, s__5fdebugName, (_imp_t)CodeGenerator___5fdebugName);
  _libid->method(v_CodeGenerator, s__5fslots, (_imp_t)CodeGenerator___5fslots);
  _libid->export("CodeGenerator", v_CodeGenerator);
 {
  oop _1= 0;
  _1= v_IdentityDictionary;
  _line(28);
  _1=_sendv(s_new, 1, _1);
  v_CodeGenerators= _1;
  _libid->export("CodeGenerators", v_CodeGenerators);
 }
  l_3= _sendv(s_size_5f_value_5f_, 3, v_ImmutableString, 38, "no code generator available for model ");
  _libid->method(v_CodeGenerator, s_forExecutionModel_, (_imp_t)CodeGenerator__forExecutionModel_);
  l_5= _sendv(s_value_5f_, 2, v_SmallInteger, 0);
  _libid->method(v_CodeGenerator, s_withCompiler_encoder_, (_imp_t)CodeGenerator__withCompiler_encoder_);
  _libid->method(v_CodeGenerator, s_encoder, (_imp_t)CodeGenerator__encoder);
  _leave();
}
