/* generated by Id 1.1 at ü */
/* with the command: -I../stage1/ -I../st80 -c ParseNode.st -o ../stage2/ParseNode.o.c */

#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <setjmp.h>
#include <string.h>
#include <ctype.h>
#include <fcntl.h>
#include <unistd.h>
#include <time.h>
#include <sys/time.h>
#include <sys/stat.h>
#include <sys/param.h>
#include <assert.h>
#define GC_DLL 1
#include <gc/gc.h>
#if defined(WIN32)
# include <malloc.h>
# include <windows.h>
  typedef HINSTANCE dlhandle_t;
#else
# include <dlfcn.h>
  typedef void *dlhandle_t;
#endif
#ifndef O_BINARY
# define O_BINARY 0
#endif

typedef struct t__object *oop;

struct __send;
typedef oop (*_imp_t)(struct __send *_send, ...);

#include <id/id.h>

static struct __libid *_libid= 0;

#ifdef ID_DEBUG
# define _enter(info) void *__id_debug= _libid->enter(info)
# define _line(lno)			_libid->line(lno)
# define _leave()			_libid->leave(__id_debug)
# define _backtrace()			_libid->backtrace()
#else
# define _enter(info)			(void)info
# define _line(lno)
# define _leave()
# define _backtrace()			"(no debugging information)"
#endif
#define _return			_leave(); return

#define _sendv(MSG, N, RCV, ARG...) ({					\
  struct __send _s= { (MSG), (N), (RCV) };				\
  ((_imp_t)(_libid->bindv(&_s)))(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

#define _superv(TYP, MSG, N, RCV, ARG...) ({	\
  struct __send _s= { (MSG), (N), (TYP) };	\
  _imp_t _imp= _libid->bindv(&_s);		\
  _s.receiver= (RCV);				\
  _imp(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

static oop s_position= 0;
static oop s_location= 0;
static oop s_withPosition_= 0;
static oop s__5fdebugName= 0;
static oop s_size_5f_value_5f_= 0;
static oop s_new= 0;
static oop s__5fimport_= 0;
static oop s_printString= 0;
static oop s_printIndent_= 0;
static oop s_timesRepeat_= 0;
static oop s_put= 0;
static oop s_function_5f_arity_5f_= 0;
static oop s_println_= 0;
static oop s_initialize= 0;
static oop s__5fslots= 0;
static oop s__2c= 0;
static oop s_error_= 0;
static oop s_location_= 0;
static oop s__5fsizeof= 0;
static oop s_println= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { "position", &s_position },
  { "location", &s_location },
  { "withPosition:", &s_withPosition_ },
  { "_debugName", &s__5fdebugName },
  { "size_:value_:", &s_size_5f_value_5f_ },
  { "new", &s_new },
  { "_import:", &s__5fimport_ },
  { "printString", &s_printString },
  { "printIndent:", &s_printIndent_ },
  { "timesRepeat:", &s_timesRepeat_ },
  { "put", &s_put },
  { "function_:arity_:", &s_function_5f_arity_5f_ },
  { "println:", &s_println_ },
  { "initialize", &s_initialize },
  { "_slots", &s__5fslots },
  { ",", &s__2c },
  { "error:", &s_error_ },
  { "location:", &s_location_ },
  { "_sizeof", &s__5fsizeof },
  { "println", &s_println },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Character {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Fraction {
  struct _vtable *_vtable[0];
  oop v_numerator;
  oop v_denominator;
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargePositiveInteger {
  struct _vtable *_vtable[0];
  oop v_bytes;
};
struct t_LargeNegativeInteger {
  struct _vtable *_vtable[0];
  oop v_bytes;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_ImmutableArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_WordArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__words;
};
struct t_ImmutableWordArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__words;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_ImmutableByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_ImmutableString {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
struct t_CharacterTable {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_ParseNode {
  struct _vtable *_vtable[0];
  oop v_position;
  oop v_location;
};
static oop l_4= 0;
static oop l_5= 0;
static oop l_11= 0;
static oop l_10= 0;
static oop v__object= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_StaticBlockClosure= 0;
static oop v_Magnitude= 0;
static oop v_Number= 0;
static oop v_Integer= 0;
static oop v_LargePositiveInteger= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_ArrayedCollection= 0;
static oop v_Array= 0;
static oop v_WordArray= 0;
static oop v_ByteArray= 0;
static oop v_String= 0;
static oop v_ImmutableString= 0;
static oop v_nil= 0;
static oop v_ParseNode= 0;
static size_t ParseNode___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_ParseNode); }
static char *ParseNode___5fdebugName(oop _closure, oop v_self) { return "ParseNode"; }
static struct __slotinfo *ParseNode___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "position", 0, 4 }, { "location", 4, 4 }, { 0, 0, 0 } };  return &info[0]; }
static struct __methodinfo __info1= { "withPosition:", "ParseNode", "/Users/piumarta/src/idst/object/idc/ParseNode.st", 0, 27, 33, 0 };
static oop ParseNode__withPosition_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aPosition)
 {
  _enter(&__info1);
  oop _1= 0;
  _line(27);
  _1= v_self;
  _line(29);
  _1=_superv(v_Object, s_new, 1, _1);
  v_self= _1;
  v_stateful_self= _1;
  _1= v_aPosition;
  ((struct t_ParseNode *)v_stateful_self)->v_position= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info2= { "initialize", "ParseNode", "/Users/piumarta/src/idst/object/idc/ParseNode.st", 0, 33, 39, &__info1 };
static oop ParseNode__initialize(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info2);
  oop _1= 0;
  _line(33);
  _1= v_self;
  _line(35);
  _1=_superv(v_Object, s_initialize, 1, _1);
  _1= v_nil;
  ((struct t_ParseNode *)v_stateful_self)->v_location= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info3= { "new", "ParseNode", "/Users/piumarta/src/idst/object/idc/ParseNode.st", 0, 39, 44, &__info2 };
static oop ParseNode__new(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info3);
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  _line(39);
  _1= v_self;
  _2= l_4;
  _3= v_self;
  _line(41);
  _3=_sendv(s_printString, 1, _3);
  _line(41);
  _2=_sendv(s__2c, 2, _2, _3);
  _3= l_5;
  _line(41);
  _2=_sendv(s__2c, 2, _2, _3);
  _line(41);
  _1=_sendv(s_error_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info6= { "location:", "ParseNode", "/Users/piumarta/src/idst/object/idc/ParseNode.st", 0, 44, 49, &__info3 };
static oop ParseNode__location_(oop v__closure, oop v_stateful_self, oop v_self, oop v_aLocation)
 {
  _enter(&__info6);
  oop _1= 0;
  _line(44);
  _1= v_aLocation;
  ((struct t_ParseNode *)v_stateful_self)->v_location= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info7= { "position", "ParseNode", "/Users/piumarta/src/idst/object/idc/ParseNode.st", 0, 49, 50, &__info6 };
static oop ParseNode__position(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info7);
  oop _1= 0;
  _line(49);
  _1= ((struct t_ParseNode *)v_stateful_self)->v_position;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info8= { "location", "ParseNode", "/Users/piumarta/src/idst/object/idc/ParseNode.st", 0, 50, 52, &__info7 };
static oop ParseNode__location(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info8);
  oop _1= 0;
  _line(50);
  _1= ((struct t_ParseNode *)v_stateful_self)->v_location;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info10= { "[] printIndent:", "ParseNode", "/Users/piumarta/src/idst/object/idc/ParseNode.st", 0, 52, 57, &__info8 };
static oop b_10(oop v__closure, oop v__self)
 {
  _enter(&__info10);
  oop _1= 0;
  _line(54);
  _1= l_11;
  _line(54);
  _1=_sendv(s_put, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info9= { "printIndent:", "ParseNode", "/Users/piumarta/src/idst/object/idc/ParseNode.st", 0, 52, 57, &__info10 };
static oop ParseNode__printIndent_(oop v__closure, oop v_stateful_self, oop v_self, oop v_indent)
 {
  _enter(&__info9);
  oop _1= 0;
  oop _2= 0;
  _line(52);
  _1= v_indent;
  _2= l_10;
  _line(54);
  _1=_sendv(s_timesRepeat_, 2, _1, _2);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info12= { "println:", "ParseNode", "/Users/piumarta/src/idst/object/idc/ParseNode.st", 0, 57, 62, &__info9 };
static oop ParseNode__println_(oop v__closure, oop v_stateful_self, oop v_self, oop v_indent)
 {
  _enter(&__info12);
  oop _1= 0;
  oop _2= 0;
  _line(57);
  _1= v_self;
  _2= v_indent;
  _line(59);
  _1=_sendv(s_printIndent_, 2, _1, _2);
  _1= v_self;
  _line(60);
  _1=_sendv(s_println, 1, _1);
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }

static struct __methodinfo __info= { "__id__init__", "<initialisation>", "ParseNode.st", 0, 0, 0, &__info12 };
void __id__init__ParseNode(struct __libid *__libid)
{
  if (_libid) return;
  if (!(_libid= __libid)) { fprintf(stderr, "init _libid %p\n", __libid);  abort(); }
# define GC_add_roots _libid->gc_addRoots
  GC_INIT();
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _libid->intern(s->name);
  }
  _enter(&__info);
  _libid->infos(&__info, &__info1);

  _sendv(s__5fimport_, 3, _libid->_object, "Object", "__id__init__Object");
  v__object= _libid->import("_object");
  v_Object= _libid->import("Object");
  v_UndefinedObject= _libid->import("UndefinedObject");
  v_StaticBlockClosure= _libid->import("StaticBlockClosure");
  v_Magnitude= _libid->import("Magnitude");
  v_Number= _libid->import("Number");
  v_Integer= _libid->import("Integer");
  v_LargePositiveInteger= _libid->import("LargePositiveInteger");
  v_Collection= _libid->import("Collection");
  v_SequenceableCollection= _libid->import("SequenceableCollection");
  v_ArrayedCollection= _libid->import("ArrayedCollection");
  v_Array= _libid->import("Array");
  v_WordArray= _libid->import("WordArray");
  v_ByteArray= _libid->import("ByteArray");
  v_String= _libid->import("String");
  v_ImmutableString= _libid->import("ImmutableString");
  v_nil= _libid->import("nil");
  v_ParseNode= _libid->proto2(v_Object, ParseNode___5fsizeof(0, 0));
  _libid->method(v_ParseNode, s__5fsizeof, (_imp_t)ParseNode___5fsizeof);
  _libid->method(v_ParseNode, s__5fdebugName, (_imp_t)ParseNode___5fdebugName);
  _libid->method(v_ParseNode, s__5fslots, (_imp_t)ParseNode___5fslots);
  _libid->export("ParseNode", v_ParseNode);
  _libid->method(v_ParseNode, s_withPosition_, (_imp_t)ParseNode__withPosition_);
  _libid->method(v_ParseNode, s_initialize, (_imp_t)ParseNode__initialize);
  l_4= _sendv(s_size_5f_value_5f_, 3, v_ImmutableString, 13, "instances of ");
  l_5= _sendv(s_size_5f_value_5f_, 3, v_ImmutableString, 32, " are created with #withPosition:");
  _libid->method(v_ParseNode, s_new, (_imp_t)ParseNode__new);
  _libid->method(v_ParseNode, s_location_, (_imp_t)ParseNode__location_);
  _libid->method(v_ParseNode, s_position, (_imp_t)ParseNode__position);
  _libid->method(v_ParseNode, s_location, (_imp_t)ParseNode__location);
  l_11= _sendv(s_size_5f_value_5f_, 3, v_ImmutableString, 2, "  ");
  l_10= _sendv(s_function_5f_arity_5f_, 3, v_StaticBlockClosure, b_10, 0);
  _libid->method(v_ParseNode, s_printIndent_, (_imp_t)ParseNode__printIndent_);
  _libid->method(v_ParseNode, s_println_, (_imp_t)ParseNode__println_);
  _leave();
}
