/* generated by Id 1.1 at ,$ */
/* with the command: -I../stage1/ -I../st80 -c ScannerContext.st -o ../stage2/ScannerContext.o.c */

#include <id/id.h>

static struct __libid *_libid= 0;

#ifdef ID_DEBUG
# define _enter(info) void *__id_debug= _libid->enter(info)
# define _line(lno)			_libid->line(lno)
# define _leave()			_libid->leave(__id_debug)
# define _backtrace()			_libid->backtrace()
#else
# define _enter(info)			(void)info
# define _line(lno)
# define _leave()
# define _backtrace()			"(no debugging information)\n"
#endif
#define _return			_leave(); return

#define _sendv(MSG, N, RCV, ARG...) ({					\
  struct __send _s= { (MSG), (N), (RCV) };				\
  ((_imp_t)(_libid->bindv(&_s)))(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

#define _superv(TYP, MSG, N, RCV, ARG...) ({	\
  struct __send _s= { (MSG), (N), (TYP) };	\
  _imp_t _imp= _libid->bindv(&_s);		\
  _s.receiver= (RCV);				\
  _imp(&_s, _s.receiver, _s.receiver, ##ARG);	\
})

static oop s_next= 0;
static oop s_onFileNamed_= 0;
static oop s__5fdebugName= 0;
static oop s_value_5f_= 0;
static oop s_peek= 0;
static oop s_new= 0;
static oop s__5fimport_= 0;
static oop s_atEnd= 0;
static oop s_readStream= 0;
static oop s_fileContents= 0;
static oop s_file= 0;
static oop s_line= 0;
static oop s__5fslots= 0;
static oop s_ifTrue_= 0;
static oop s__2b= 0;
static oop s__3d_3d= 0;
static oop s__5fsizeof= 0;
static struct _Selector { const char *name; oop *addr; } _Selectors[]= {
  { "next", &s_next },
  { "onFileNamed:", &s_onFileNamed_ },
  { "_debugName", &s__5fdebugName },
  { "value_:", &s_value_5f_ },
  { "peek", &s_peek },
  { "new", &s_new },
  { "_import:", &s__5fimport_ },
  { "atEnd", &s_atEnd },
  { "readStream", &s_readStream },
  { "fileContents", &s_fileContents },
  { "file", &s_file },
  { "line", &s_line },
  { "_slots", &s__5fslots },
  { "ifTrue:", &s_ifTrue_ },
  { "+", &s__2b },
  { "==", &s__3d_3d },
  { "_sizeof", &s__5fsizeof },
  { 0, 0 }
};
struct t__object {
  struct _vtable *_vtable[0];
};
struct t__selector {
  struct _vtable *_vtable[0];
  oop v__size;
  oop v__elements;
};
struct t__assoc {
  struct _vtable *_vtable[0];
  oop v_key;
  oop v_value;
};
struct t__closure {
  struct _vtable *_vtable[0];
  oop v__method;
  oop v_data;
};
struct t__vector {
  struct _vtable *_vtable[0];
  oop v__size;
};
struct t__vtable {
  struct _vtable *_vtable[0];
  oop v__tally;
  oop v_bindings;
  oop v_delegate;
};
struct t_Object {
  struct _vtable *_vtable[0];
};
struct t_UndefinedObject {
  struct _vtable *_vtable[0];
};
struct t_StaticBlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
};
struct t_BlockClosure {
  struct _vtable *_vtable[0];
  oop v__function;
  oop v__arity;
  oop v_outer;
  oop v_state;
  oop v__nlr;
};
struct t_Magnitude {
  struct _vtable *_vtable[0];
};
struct t_Character {
  struct _vtable *_vtable[0];
  oop v_value;
};
struct t_Number {
  struct _vtable *_vtable[0];
};
struct t_Fraction {
  struct _vtable *_vtable[0];
  oop v_numerator;
  oop v_denominator;
};
struct t_Float {
  struct _vtable *_vtable[0];
};
struct t_Integer {
  struct _vtable *_vtable[0];
};
struct t_SmallInteger {
  struct _vtable *_vtable[0];
};
struct t_LargePositiveInteger {
  struct _vtable *_vtable[0];
  oop v_bytes;
};
struct t_LargeNegativeInteger {
  struct _vtable *_vtable[0];
  oop v_bytes;
};
struct t_Collection {
  struct _vtable *_vtable[0];
};
struct t_SequenceableCollection {
  struct _vtable *_vtable[0];
};
struct t_ArrayedCollection {
  struct _vtable *_vtable[0];
  oop v_size;
};
struct t_Array {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_ImmutableArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_WordArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__words;
};
struct t_ImmutableWordArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__words;
};
struct t_ByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_ImmutableByteArray {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_String {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_ImmutableString {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_Symbol {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__bytes;
};
struct t_nil {
  struct _vtable *_vtable[0];
};
struct t_true {
  struct _vtable *_vtable[0];
};
struct t_false {
  struct _vtable *_vtable[0];
};
struct t_CharacterTable {
  struct _vtable *_vtable[0];
  oop v_size;
  oop v__pointers;
};
struct t_ScannerContext {
  struct _vtable *_vtable[0];
  oop v_file;
  oop v_line;
  oop v_stream;
};
static oop l_2= 0;
static oop l_8= 0;
static oop l_9= 0;
static oop v__object= 0;
static oop v_Object= 0;
static oop v_UndefinedObject= 0;
static oop v_StaticBlockClosure= 0;
static oop v_Magnitude= 0;
static oop v_Character= 0;
static oop v_Number= 0;
static oop v_Integer= 0;
static oop v_SmallInteger= 0;
static oop v_LargePositiveInteger= 0;
static oop v_Collection= 0;
static oop v_SequenceableCollection= 0;
static oop v_ArrayedCollection= 0;
static oop v_Array= 0;
static oop v_WordArray= 0;
static oop v_ByteArray= 0;
static oop v_String= 0;
static oop v_ImmutableString= 0;
static oop v_true= 0;
static oop v_false= 0;
static oop v_ScannerContext= 0;
static size_t ScannerContext___5fsizeof(oop _closure, oop v_self) { return sizeof(struct t_ScannerContext); }
static char *ScannerContext___5fdebugName(oop _closure, oop v_self) { return "ScannerContext"; }
static struct __slotinfo *ScannerContext___5fslots(oop _closure, oop v_self) { static struct __slotinfo info[]= { { "file", 0, 4 }, { "line", 4, 4 }, { "stream", 8, 4 }, { 0, 0, 0 } };  return &info[0]; }
static struct __methodinfo __info1= { "onFileNamed:", "ScannerContext", "/Users/piumarta/src/idst/object/idc/ScannerContext.st", 0, 28, 36, 0 };
static oop ScannerContext__onFileNamed_(oop v__closure, oop v_stateful_self, oop v_self, oop v_pathName)
 {
  _enter(&__info1);
  oop _1= 0;
  _line(28);
  _1= v_self;
  _line(30);
  _1=_superv(v_Object, s_new, 1, _1);
  v_self= _1;
  v_stateful_self= _1;
  _1= v_pathName;
  ((struct t_ScannerContext *)v_stateful_self)->v_file= _1;
  _1= l_2;
  ((struct t_ScannerContext *)v_stateful_self)->v_line= _1;
  _1= ((struct t_ScannerContext *)v_stateful_self)->v_file;
  _line(33);
  _1=_sendv(s_fileContents, 1, _1);
  _line(33);
  _1=_sendv(s_readStream, 1, _1);
  ((struct t_ScannerContext *)v_stateful_self)->v_stream= _1;
  _1= v_self;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info3= { "file", "ScannerContext", "/Users/piumarta/src/idst/object/idc/ScannerContext.st", 0, 36, 37, &__info1 };
static oop ScannerContext__file(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info3);
  oop _1= 0;
  _line(36);
  _1= ((struct t_ScannerContext *)v_stateful_self)->v_file;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info4= { "line", "ScannerContext", "/Users/piumarta/src/idst/object/idc/ScannerContext.st", 0, 37, 38, &__info3 };
static oop ScannerContext__line(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info4);
  oop _1= 0;
  _line(37);
  _1= ((struct t_ScannerContext *)v_stateful_self)->v_line;
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info5= { "atEnd", "ScannerContext", "/Users/piumarta/src/idst/object/idc/ScannerContext.st", 0, 38, 39, &__info4 };
static oop ScannerContext__atEnd(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info5);
  oop _1= 0;
  _line(38);
  _1= ((struct t_ScannerContext *)v_stateful_self)->v_stream;
  _line(38);
  _1=_sendv(s_atEnd, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info6= { "peek", "ScannerContext", "/Users/piumarta/src/idst/object/idc/ScannerContext.st", 0, 39, 41, &__info5 };
static oop ScannerContext__peek(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info6);
  oop _1= 0;
  _line(39);
  _1= ((struct t_ScannerContext *)v_stateful_self)->v_stream;
  _line(39);
  _1=_sendv(s_peek, 1, _1);
  _leave();
  return _1;
  _leave();
 }
static struct __methodinfo __info7= { "next", "ScannerContext", "/Users/piumarta/src/idst/object/idc/ScannerContext.st", 0, 41, 47, &__info6 };
static oop ScannerContext__next(oop v__closure, oop v_stateful_self, oop v_self)
 {
  _enter(&__info7);
  oop v_c= 0;
  oop _1= 0;
  oop _2= 0;
  oop _3= 0;
  (void)v_c;
  _line(41);
  /* ifTrue: */
  _1= 0;
  _2= ((struct t_ScannerContext *)v_stateful_self)->v_stream;
  _line(44);
  _2=_sendv(s_next, 1, _2);
  v_c= _2;
  _3= l_8;
  _2= (_2 == _3) ? v_true : v_false;
  if (!_2) goto _l1;
 {
  _1= ((struct t_ScannerContext *)v_stateful_self)->v_line;
  _2= l_9;
  {
    int _l= (long)_1 >> 1;
    int _r= (long)_2 >> 1;
    int _s= _l + _r;
    if ((1 & (long)_1) && ((_s ^ (_s << 1)) >= 0))  _1= (oop)(long)(_s << 1 | 1);  else _1= _sendv(s__2b, 2, _1, _2);
  }
  ((struct t_ScannerContext *)v_stateful_self)->v_line= _1;
 }
 _l1:;
  _1= v_c;
  _leave();
  return _1;
  _leave();
 }

static struct __methodinfo __info= { "__id__init__", "<initialisation>", "ScannerContext.st", 0, 0, 0, &__info7 };
void __id__init__ScannerContext(struct __libid *__libid)
{
  if (_libid) return;
  if (!(_libid= __libid)) { fprintf(stderr, "init _libid %p\n", __libid);  abort(); }
# define GC_add_roots _libid->gc_addRoots
  GC_INIT();
  {
    struct _Selector *s= 0;
    for (s= _Selectors;  s->name;  ++s)
      *s->addr= _libid->intern(s->name);
  }
  _enter(&__info);
  _libid->infos(&__info, &__info1);

  _sendv(s__5fimport_, 3, _libid->_object, "Object", "__id__init__Object");
  v__object= _libid->import("_object");
  v_Object= _libid->import("Object");
  v_UndefinedObject= _libid->import("UndefinedObject");
  v_StaticBlockClosure= _libid->import("StaticBlockClosure");
  v_Magnitude= _libid->import("Magnitude");
  v_Character= _libid->import("Character");
  v_Number= _libid->import("Number");
  v_Integer= _libid->import("Integer");
  v_SmallInteger= _libid->import("SmallInteger");
  v_LargePositiveInteger= _libid->import("LargePositiveInteger");
  v_Collection= _libid->import("Collection");
  v_SequenceableCollection= _libid->import("SequenceableCollection");
  v_ArrayedCollection= _libid->import("ArrayedCollection");
  v_Array= _libid->import("Array");
  v_WordArray= _libid->import("WordArray");
  v_ByteArray= _libid->import("ByteArray");
  v_String= _libid->import("String");
  v_ImmutableString= _libid->import("ImmutableString");
  v_true= _libid->import("true");
  v_false= _libid->import("false");
  v_ScannerContext= _libid->proto2(v_Object, ScannerContext___5fsizeof(0, 0));
  _libid->method(v_ScannerContext, s__5fsizeof, (_imp_t)ScannerContext___5fsizeof);
  _libid->method(v_ScannerContext, s__5fdebugName, (_imp_t)ScannerContext___5fdebugName);
  _libid->method(v_ScannerContext, s__5fslots, (_imp_t)ScannerContext___5fslots);
  _libid->export("ScannerContext", v_ScannerContext);
  l_2= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_ScannerContext, s_onFileNamed_, (_imp_t)ScannerContext__onFileNamed_);
  _libid->method(v_ScannerContext, s_file, (_imp_t)ScannerContext__file);
  _libid->method(v_ScannerContext, s_line, (_imp_t)ScannerContext__line);
  _libid->method(v_ScannerContext, s_atEnd, (_imp_t)ScannerContext__atEnd);
  _libid->method(v_ScannerContext, s_peek, (_imp_t)ScannerContext__peek);
  l_8= _sendv(s_value_5f_, 2, v_Character, 10);
  l_9= _sendv(s_value_5f_, 2, v_SmallInteger, 1);
  _libid->method(v_ScannerContext, s_next, (_imp_t)ScannerContext__next);
  _leave();
}
